# Change these first
owner: happy-doc
repo: HappyStatus

sites:
  - name: Web App
    url: https://app.gohappydoc.com
  - name: Transcription
    url: https://service.gohappydoc.com/service-transcribe/healthcheck
  - name: Document Generation
    url: https://service.gohappydoc.com/api-server/healthcheck
  - name: OpenAI
    url: https://status.openai.com/api/v2/status.json
  - name: Database
    url: https://supa.happydoc.ai/rest/v1/app_versions?id=eq.1
    headers:
      - "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"
      - "apiKey: ${{ secrets.SUPABASE_KEY }}"
      - "Content-Type: application/json"

status-website:
  cname: status.gohappydoc.com
  logoUrl: https://status.gohappydoc.com/favicon.png
  favicon: https://status.gohappydoc.com/favicon.png
  themeUrl: https://status.gohappydoc.com/theme.css
  name: HappyStatus
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
