# Change these first
owner: happy-doc
repo: HappyStatus

sites:
  - name: Transcription
    url: https://service.gohappydoc.com/service-transcribe/healthcheck
  - name: Document Generation
    url: https://service.gohappydoc.com/api-server/healthcheck
  - name: OpenAI
    url: https://status.openai.com/api/v2/status.json

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.gohappydoc.com
  # baseUrl: /HappyStatus
  logoUrl: https://happy-doc.github.io/HappyStatus/favicon.png
  name: HappyStatus
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
